stats:
  cron: "0 */3 * * *"
  queue: cron
  class: CronTask
  args: "stats"
  description: Fetches activities from FitBit service
  rails_envs: development, production, staging

devices:
  cron: "30 0,6 * * *"
  queue: cron
  class: CronTask
  args: "devices"
  description: Fetches FitBit devices info
  rails_envs: development, production, staging